---
driver:
  name: vagrant
  customize:
    memory: 512
    cpus: 2

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[esruby::default]
    attributes:
