---
driver:
  name: vagrant
  network:
    - ["private_network", { ip: "10.1.3.8" }]
  synced_folders:
    # - ["../cmput391", "/cmput391", "created: true"]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[esruby::default]
    attributes:
