---
driver:
  name: vagrant
  customize:
    memory: 512
    cpus: 2
  network:
    - ["private_network", { ip: "10.1.3.8" }]
  synced_folders:
    - ["../cs391", "/cs391", "create: true"]

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - role[dev]
      - recipe[esruby::default]
    attributes:
