#!/usr/bin/env bash
echo "Uploading cluster.json"
export HOST=199.116.235.83
export SSH_OPTIONS="-o User=user -i ~/.ssh/391project.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

scp $SSH_OPTIONS cluster.json $HOST:
ssh -t $SSH_OPTIONS $HOST \
      "curl -# -L -k -o /tmp/esruby-master.tar.gz https://github.com/derekdowling/esruby/archive/master.tar.gz"

echo "Installing chef/berkshelf"
time ssh -t $SSH_OPTIONS $HOST <<END
    sudo apt-get update
    sudo apt-get install build-essential curl git vim -y
    curl -# -L http://www.opscode.com/chef/install.sh | sudo bash -s --
    sudo mkdir -p /etc/chef/; sudo mkdir -p /var/chef/cookbooks/esruby
    sudo tar --strip 1 -C /var/chef/cookbooks/esruby -xf /tmp/esruby-master.tar.gz
    sudo apt-get install bison zlib1g-dev libopenssl-ruby1.9.1 libssl-dev libyaml-0-2 libxslt-dev libxml2-dev libreadline-gplv2-dev libncurses5-dev file ruby1.9.1-dev git --yes --fix-missing
    sudo /opt/chef/embedded/bin/gem install berkshelf --version 2.0.14 --no-rdoc --no-ri
    sudo /opt/chef/embedded/bin/berks install --path=/var/chef/cookbooks/ --berksfile=/var/chef/cookbooks/esruby/Berksfile
END

echo "Installing cookbooks"
ssh -t $SSH_OPTIONS $HOST "sudo chef-solo -N 391-Cluster-0 -j node.json"

echo "Finished, checking cluster:"
ssh $SSH_OPTIONS $HOST "curl localhost:9200"
