#!/usr/bin/env bash
echo "Uploading cluster.json"
def_host=199.116.235.83
# export SSH_OPTIONS="-o User=user -i /Users/derek/.ssh/391project.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
export HOST=${1:-$def_host}

ssh -t $SSH_OPTIONS $HOST \
      "curl -# -L -k -o git clone https://github.com/derekdowling/esruby"

echo "ssh -i ~/.ssh/391project.pem user@199.116.235.83"
