#!/usr/bin/env bash
echo "Uploading cluster.json"
curl -# -L -k -o /tmp/esruby-master.tar.gz https://github.com/derekdowling/esruby/archive/master.tar.gz

echo "Installing chef/berkshelf"
sudo apt-get update
sudo apt-get install build-essential curl git vim -y
curl -# -L http://www.opscode.com/chef/install.sh | sudo bash -s --
sudo mkdir -p /etc/chef
sudo mkdir -p /var/chef/cookbooks/esruby
sudo tar --strip 1 -C /var/chef/cookbooks/esruby -xf /tmp/esruby-master.tar.gz
sudo apt-get install bison zlib1g-dev libopenssl-ruby1.9.1 libssl-dev libyaml-0-2 libxslt-dev libxml2-dev libreadline-gplv2-dev libncurses5-dev file ruby1.9.1-dev git --yes --fix-missing
sudo gem install berkshelf --no-rdoc --no-ri
sudo berks vendor /var/chef/cookbooks/ -b /var/chef/cookbooks/esruby/Berksfile
sudo chef-solo -N 391-Cluster -j cluster.json -c /var/chef/cookbooks/esruby/solo.rb

curl localhost:9200
